# Generated by Django 4.2.30 on 2026-05-04 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('category', models.CharField(choices=[('news', 'Company News'), ('insight', 'Industry Insight'), ('tutorial', 'How-To Guide'), ('case-study', 'Case Study Spotlight'), ('event', 'Event Announcement')], default='insight', max_length=20)),
                ('excerpt', models.CharField(help_text='Short preview shown in card', max_length=320)),
                ('body', models.TextField(help_text='Full article content (HTML allowed)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('author', models.CharField(default='AI-Solution Team', max_length=120)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_time_min', models.PositiveSmallIntegerField(default=5, verbose_name='Read time (minutes)')),
            ],
            options={
                'verbose_name': 'Article',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=160, verbose_name='Client / Organisation')),
                ('industry', models.CharField(max_length=100)),
                ('challenge', models.TextField(verbose_name='The Challenge')),
                ('solution', models.TextField(verbose_name='Our Solution')),
                ('outcome', models.TextField(verbose_name='Results & Impact')),
                ('metric_label', models.CharField(blank=True, help_text="e.g. 'Reduction in handling time'", max_length=60)),
                ('metric_value', models.CharField(blank=True, help_text="e.g. '42%'", max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='case_studies/')),
                ('published_at', models.DateField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Case Study',
                'verbose_name_plural': 'Case Studies',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('user_msg', models.TextField(verbose_name='User Message')),
                ('bot_reply', models.TextField(verbose_name='Bot Reply')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone Number')),
                ('company', models.CharField(blank=True, max_length=150, verbose_name='Company / Organisation')),
                ('country', models.CharField(max_length=80, verbose_name='Country')),
                ('job_title', models.CharField(max_length=120, verbose_name='Job Title')),
                ('job_details', models.TextField(verbose_name='How can we help?')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('is_read', models.BooleanField(default=False, verbose_name='Marked as Read')),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('event_type', models.CharField(choices=[('conference', 'Conference'), ('workshop', 'Workshop'), ('launch', 'Product Launch'), ('networking', 'Networking Event'), ('award', 'Award Ceremony'), ('other', 'Other')], default='other', max_length=20)),
                ('event_date', models.DateField(help_text='Date of the event')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_upcoming', models.BooleanField(default=False, verbose_name='Is Upcoming Event?')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('icon', models.CharField(choices=[('robot', '🤖 AI Assistant'), ('chart', '📊 Analytics'), ('shield', '🛡️ Security'), ('workflow', '⚙️ Workflow'), ('integration', '🔗 Integration'), ('support', '💬 Support')], default='robot', max_length=20)),
                ('summary', models.CharField(help_text='One-line pitch shown on cards', max_length=300)),
                ('description', models.TextField(help_text='Full rich-text description')),
                ('features', models.TextField(blank=True, help_text='Bullet points, one per line')),
                ('is_featured', models.BooleanField(default=False, help_text='Show prominently on homepage')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Solution',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=120)),
                ('author_title', models.CharField(help_text="e.g. 'Head of IT, Acme Corp'", max_length=160, verbose_name='Job Title & Company')),
                ('author_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('quote', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Star Rating (1–5)')),
                ('is_approved', models.BooleanField(default=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'ordering': ['-rating', '-submitted_at'],
            },
        ),
    ]
