# Generated by Django 5.2.7 on 2026-05-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default='Wearbridge Team', max_length=120),
        ),
        migrations.AlterField(
            model_name='solution',
            name='icon',
            field=models.CharField(choices=[('robot', 'Staff Help Desk'), ('chart', '📊 Analytics'), ('shield', '🛡️ Security'), ('workflow', '⚙️ Workflow'), ('integration', '🔗 Integration'), ('support', '💬 Support')], default='robot', max_length=20),
        ),
    ]
