# Generated by Django 5.2.7 on 2026-05-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_article_author_alter_solution_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default='AI Solutions Team', max_length=120),
        ),
    ]
