# Generated by Django 5.2.7 on 2026-06-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_article_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('conference', 'Conference'), ('workshop', 'Workshop'), ('launch', 'Product Launch'), ('networking', 'Networking Event'), ('award', 'Award Ceremony'), ('other', 'Other')], default='other', max_length=20)),
                ('event_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('registration_label', models.CharField(default='Register interest', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Upcoming Event',
                'verbose_name_plural': 'Upcoming Events',
                'ordering': ['event_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Company Article', 'verbose_name_plural': 'Company Articles'},
        ),
        migrations.AlterModelOptions(
            name='casestudy',
            options={'ordering': ['-published_at'], 'verbose_name': 'Industry Highlight', 'verbose_name_plural': 'Industry Highlights'},
        ),
        migrations.AlterModelOptions(
            name='contactinquiry',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Customer Inquiry', 'verbose_name_plural': 'Customer Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['-event_date'], 'verbose_name': 'Event Gallery Photo', 'verbose_name_plural': 'Event Gallery Photos'},
        ),
        migrations.AlterModelOptions(
            name='solution',
            options={'ordering': ['display_order', 'title'], 'verbose_name': 'Software Solution', 'verbose_name_plural': 'Software Solutions'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-rating', '-submitted_at'], 'verbose_name': 'Customer Feedback', 'verbose_name_plural': 'Customer Feedback'},
        ),
    ]
