# Generated by Django 5.2.7 on 2026-06-07 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_promotionalevent_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='casestudy',
            options={'ordering': ['-published_at'], 'verbose_name': 'Highlight', 'verbose_name_plural': 'Highlights'},
        ),
        migrations.AlterModelOptions(
            name='contactinquiry',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Inquiry', 'verbose_name_plural': 'Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['-event_date'], 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.AlterModelOptions(
            name='promotionalevent',
            options={'ordering': ['event_date'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='solution',
            options={'ordering': ['display_order', 'title'], 'verbose_name': 'Solution', 'verbose_name_plural': 'Solutions'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-rating', '-submitted_at'], 'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedback'},
        ),
    ]
