# Generated by Django 5.2.7 on 2026-06-07 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_article_options_alter_casestudy_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinquiry',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Query', 'verbose_name_plural': 'Queries'},
        ),
    ]
