# Generated by Django 5.2.15 on 2026-07-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_article_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionalevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
    ]
